# Generated by Django 4.2.1 on 2023-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='image',
            field=models.ImageField(upload_to='img/02.png'),
        ),
    ]
