# Generated by Django 4.2.1 on 2023-06-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0005_alter_projecto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
