# Generated by Django 4.2.1 on 2023-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0010_alter_projecto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
