# Generated by Django 4.2.1 on 2023-07-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0012_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
