# Generated by Django 4.2.1 on 2023-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0013_alter_presentacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
