# Generated by Django 3.2.6 on 2023-11-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0014_alter_presentacion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgpresent',
            fields=[
                ('imagen', models.ImageField(upload_to='media/Portafolio/images')),
                ('title', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
