# Generated by Django 3.2.6 on 2023-11-30 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0016_alter_imgpresent_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgpresent',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portafolio.presentacion'),
        ),
    ]
