# Generated by Django 3.2.6 on 2023-11-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0019_imgpresent_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgpresent',
            name='url',
        ),
    ]
