# Generated by Django 3.2.6 on 2023-12-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0023_alter_imgpresent_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgpresent',
            name='autoplay',
            field=models.BooleanField(default=True),
        ),
    ]
