# Generated by Django 3.2.6 on 2023-12-02 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0024_imgpresent_autoplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgpresent',
            name='autoplay',
        ),
    ]
