# Generated by Django 3.2.6 on 2023-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0025_remove_imgpresent_autoplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fomulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(max_length=300)),
            ],
        ),
    ]
