# Generated by Django 3.2.6 on 2023-12-21 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0026_fomulario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fomulario',
            new_name='Contacto',
        ),
    ]
