# Generated by Django 3.2.6 on 2023-12-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portafolio', '0027_rename_fomulario_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
