# Generated by Django 5.0 on 2024-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='habilit',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
