# Generated by Django 5.0 on 2024-01-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_habilit_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
